apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-mcp-server
  namespace: kubernetes-mcp-server
  labels:
    app.kubernetes.io/name: kubernetes-mcp-server
    app.kubernetes.io/version: v0.0.51
